### ISSUE TITLE
erro 177 and module

### ISSUE THREAD

**Issue by Fr-Dae** [cryzed/Twitch-IRC-Userlist-Fix#5]
hi, i have 2 error with your script

Linux version 4.15.0-72-generic (buildd@lcy01-amd64-026) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
"Lubuntu" (with lxde)

and
hexchat 2.14.1
and python3.4 on.

    [20:39:40]    File "/home/msi/.config/hexchat/addons/twitch-irc-userlist-fix.py", line 177
    [20:39:40]      print __module_name__, __module_version__, 'loaded successfully.'
    [20:39:40]                          ^
    [20:39:40]  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__module_name__, __module_version__, 'loaded successfully.')?
    [20:39:40]  Error loading module /home/msi/.config/hexchat/addons/twitch-irc-userlist-fix.py

if i make ligne 177 on comment (#) i have this return

    [21:13:07]  Traceback (most recent call last):
    [21:13:07]    File "/home/msi/.config/hexchat/addons/twitch-irc-userlist-fix.py", line 2, in <module>
    [21:13:07]      import urllib2
    [21:13:07]  ModuleNotFoundError: No module named 'urllib2'
    [21:13:07]  Error loading module /home/msi/.config/hexchat/addons/twitch-irc-userlist-fix.py

**Comment by cryzed** [comment]
Yes, this module is really old and for Python 2 - it would first have to be ported the more recent Python 3 version. Unfortunately I don't use HexChat or this method of connecting to Twitch channels anymore - so I don't have plans on doing this myself.
